# weights: ./work_dir/recognition/custom_skeleten/ST_GCN_finetuning/epoch50_model.pt
# weights: ./work_dir/recognition/custom_skeleten/ST_GCN_fixed_feature_extractor/epoch50_model.pt
# weights: ./work_dir/recognition/custom_skeleten/ST_GCN_sp_finetuning/epoch50_model.pt
# weights: ./work_dir/recognition/custom_skeleten/ST_GCN_spemn_finetuning/epoch50_model.pt
weights: ./work_dir/recognition/custom_skeleten/ST_GCN_spemn_chooseComplete_finetuning/epoch50_model.pt
# weights: ./work_dir/recognition/custom_skeleten/ST_GCN_spemn_chooseComplete_extraData_finetuning/epoch50_model.pt
model_fps: 30

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
    
# training
device: [0]